### PR TITLE
Add database interaction assertions

### PR DESCRIPTION
**Pull request by owenvoke**
Should be able to rebase this after https://github.com/pestphp/pest-plugin-laravel/pull/3 has been merged. 👍

### CODE REVIEW

**Comment by nunomaduro** [comment]
Can't why rebase from the UI? 😢

**Comment by owenvoke** [comment]
Don't think so. Give me a sec and I'll do it. :+1:

**Comment by owenvoke** [comment]
Trying to work out what other assertions should be added.

Looks like most of them are actually on the facades, etc.

**Comment by nunomaduro** [comment]
Great, thanks!

**Pull request merged**
