### PR TITLE
IDE compatibility for plugin expectations

### PR DESCRIPTION
**Pull request by mertasan**
Please watch the video. Thanks.

refs: 
https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html
https://github.com/bmewburn/vscode-intelephense#intelephense

https://user-images.githubusercontent.com/13007665/125004888-29a51180-e063-11eb-89e6-4375f0340000.mov

### CODE REVIEW

**Comment by nunomaduro** [comment]
@olivernybroe Is this a good idea?

**Comment by olivernybroe** [comment]
@nunomaduro So I got a bit of mixed feelings about this. 

This is an approach that works, however it requires the plugins to have IDE specific code in them. 
I have something close to this working in phpstorm, however this config works for both phpstorm and vscode 🤔 

PHPSTORM_META files are great as they are natively supported by phpstorm and they are trying to push them more and more. 

This however doesn't give the full support we want as doing the following will not work
```
$collection = collect(['a', 'b', 'c']);
expect($collection)->toHaveCount(3)
        ->and($collection)->toBeCollection();
```

**Comment by mertasan** [comment]
I think I fixed it. :/


https://user-images.githubusercontent.com/13007665/125052121-4c0f4d00-e0ac-11eb-970f-e23771329f57.mov

**Comment by olivernybroe** [comment]
@mertasan Don't know why, but it's not working for me 😢 
image

**Comment by mertasan** [comment]
Is your PhpStorm the latest version? @olivernybroe 

Maybe a few more people should test this out. 🤔

@nunomaduro Can you test this?

screenshot 63
screenshot 64

**Comment by nunomaduro** [comment]
@olivernybroe This would be fixed by adding the `extends` support to your plugin right? Do you have an ETA on this?

**Comment by olivernybroe** [comment]
https://github.com/pestphp/pest-intellij/pull/135 

I got a PR open for it and got pretty far with it. However before making the last stuff needed to finish it, I wanna hear with Adel if there are any big performance issues with my approach... 

However one advantage this solution suggested here has, is that it works for both phpstorm and vscode though. 

But to answer your question, no ETA yet unfortunately, if Adel approves the way to do it, I will build the rest of it and then it needs a small testing period 👍

**Comment by mertasan** [comment]
Wow! this is awesome. @olivernybroe  

@nunomaduro It would be great to support this with the pest-intellij plugin. But this works instantly for anyone who hasn't installed the pest-intellij plugin. People who are new to using the Pest packages will have a very positive effect on their first impression. (and as Oliver said it works for VSCode too.)

**Comment by olivernybroe** [comment]
@mertasan I think the biggest problem I have with this is adding a new class which is actually just a type hint class, it doesn't really exist 🙂
Next is that it is more stuff to remember to maintain for the them and something that if we do should be done on all packages. 

However it is much easier for a new user 🙂

**Pull request closed without merging**
