### PR TITLE
feat: Add Support for `Laravel` 9

### PR DESCRIPTION
**Pull request by xiCO2k**
This PR add's the support to `Laravel` v9.0.

Thanks,
Francisco

### CODE REVIEW

**Comment by owenvoke** [comment]
@xiCO2k, any thoughts on the PHPStan errors? I think it might be related to https://getcomposer.org/doc/06-config.md#allow-plugins, and requiring the `allow-plugins` key for the `pestphp/pest-plugin` package.

**Comment by nunomaduro** [comment]
@xiCO2k Can you fix / ignore the type errors?

**Comment by xiCO2k** [comment]
Sure thing.

**Comment by xiCO2k** [comment]
It seems to be related with PHPStan Level 9, that's why it it did not happen before PHPStan v1.0.

Probably best to have a different PR to handle this upgrade.

**Review by owenvoke — APPROVED** [review]
LGTM!

**Comment by nunomaduro** [comment]
Can one of you tag this release?

**Comment by owenvoke** [comment]
Sure, give me 11 mins. Got to finish work. 👍🏻 😄

**Comment by xiCO2k** [comment]
no worries :D

**Comment by owenvoke** [comment]
@xiCO2k, now tagged as `v1.2.0` 👍🏻 Let me know if you need anything else.

**Pull request merged**
